### ISSUE TITLE
`HdfsCsvDataSourceAcceptance` tests fail in a Windows environment

### ISSUE THREAD

**Issue by HADDADENICAR** [opencypher/cypher-for-apache-spark#553] opened 2018-07-12 14:39 UTC
i get an error while building the project whith `mvn clean install`:

    
The currently active SparkContext was created at:

    (No active SparkContext.)
     at org.apache.spark.SparkContext.assertNotStopped(SparkContext.scala:100)
     at org.apache.spark.SparkContext.broadcast(SparkContext.scala:1485)
     at   org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anonfun$relationFuture$1$$anonfun$apply$1.apply(BroadcastExchangeExec.scala:95)
     at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anonfun$relationFuture$1$$anonfun$apply$1.apply(BroadcastExchangeExec.scala:73)
     at org.apache.spark.sql.execution.SQLExecution$.withExecutionId(SQLExecution.scala:103)
     at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anonfun$relationFuture$1.apply(BroadcastExchangeExec.scala:72)
     at org.apache.spark.sql.execution.exchange.BroadcastExchangeExec$$anonfun$relationFuture$1.apply(BroadcastExchangeExec.scala:72)
     at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
     at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
     at java.lang.Thread.run(Thread.java:748)
    - constructs a new node *** FAILED ***
    org.apache.spark.sql.catalyst.errors.package$TreeNodeException: execute, tree:
     Exchange hashpartitioning(n __ NODE#94690L, 5)
     +- *HashAggregate(keys=[n __ NODE#94690L], functions=[], output=[n __ NODE#94690L])
      +- *SerializeFromObject [validateexternaltype(getexternalrowfield(assertnotnull(input[0,     org.apache.spark.sql.Row, true]), 0, n __ NODE), LongType) AS n __ NODE#94690L]
      +- MapPartitions <function1>, obj#94689: org.apache.spark.sql.Row
         +- DeserializeToObject createexternalrow(a __ NODE @ session_tmp#82#94684L, StructField(a __    NODE @ session_tmp#82,LongType,false)), obj#94688: org.apache.spark.sql.Row
            +- LocalTableScan [a __ NODE @ session_tmp#82#94684L]
     at org.apache.spark.sql.catalyst.errors.package$.attachTree(package.scala:56)
     at org.apache.spark.sql.execution.exchange.ShuffleExchange.doExecute(ShuffleExchange.scala:115)
     at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
     at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
     at org.apache.spark.sql.execution.Spark

**Comment by s1ck** [comment] 2018-07-12 17:55
What are the steps you took? Running `mvn clean install` on a freshly cloned master branch be fine.

**Comment by HADDADENICAR** [comment] 2018-07-12 17:59
I Just downloaded the project, then  

    $cd cypher_project_master
    $mvn clean install

**Comment by DarthMax** [comment] 2018-07-12 20:23
Can you make sure you are compiling this with Java 8. We currently only support this version.

**Comment by pstutz** [comment] 2018-07-13 10:37
Thanks a lot for reporting this. We traced it back to a resource leak. Fix is in this PR: https://github.com/opencypher/cypher-for-apache-spark/pull/556

**Comment by s1ck** [comment] 2018-07-13 11:52
@HADDADENICAR could you please verify if it works now. Thank you for reporting it.

**Comment by HADDADENICAR** [comment] 2018-07-13 14:58
i re-downloaded the project  and executed mvn clean install and i get this error now :

    [INFO] Cypher for Apache Spark - Test Utilities ........... FAILURE [  01:23 h]
    [INFO] Collection of examples for Cypher for Apache Spark . SKIPPED
    [INFO] Cypher for Apache Spark - TCK 1.0.0-SNAPSHOT ....... SKIPPED
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 02:19 h
    [INFO] Finished at: 2018-07-13T15:52:44+01:00
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:2.0.0:test (test) on project spark- cypher-testing: There are test failures -> [Help 1]
    [ERROR]
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR]
    [ERROR] For more information about the errors and possible solutions, please read the following  articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
    [ERROR]
    [ERROR] After correcting the problems, you can resume the build with the command
    [ERROR]   mvn <goals> -rf :spark-cypher-testing

**Comment by pstutz** [comment] 2018-07-13 16:44
Thanks a lot for reporting back. Which test fails and how? I could unfortunately not reproduce the problem.

**Comment by HADDADENICAR** [comment] 2018-07-13 18:56
Apparently in a test named HdfsCsvDataSourceAcceptance this is where the run fail :
    
     HdfsCsvDataSourceAcceptance:
     Formatting using clusterid: testClusterID
     Data exists in Storage Directory \tmp\hadoop\dfs\name. Formatting anyway.
      2018-07-13 19:26:08,983 WARN  [ScalaTest-main-running-HdfsCsvDataSourceAcceptance]   impl.MetricsConfig (MetricsConfig.java:loadFirst(125)) - Cannot locate configuration: tried hadoop-metrics2-namenode.properties,hadoop-metrics2.properties
       2018-07-13 19:26:10,462 WARN  [ScalaTest-main-running-HdfsCsvDataSourceAcceptance] http.HttpRequestLog (HttpRequestLog.java:getRequestLog(100)) - Jetty request log can only be enabled using Log4j
       2018-07-13 19:26:18,111 WARN  [ScalaTest-main-running-HdfsCsvDataSourceAcceptance] namenode.FSNamesystem (FSNamesystem.java:checkConfiguration(652)) - Only one namespace edits storage directory (dfs.namenode.edits.dir) configured. Beware of data loss due to lack of redundant storage directories!
      *** RUN ABORTED ***
     java.lang.UnsatisfiedLinkError: org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Ljava/lang/String;I)Z
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access0(Native Method)
        at org.apache.hadoop.io.nativeio.NativeIO$Windows.access(NativeIO.java:609)
        at org.apache.hadoop.fs.FileUtil.canWrite(FileUtil.java:996)
        at org.apache.hadoop.hdfs.server.common.Storage$StorageDirectory.analyzeStorage(Storage.java:490)
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverStorageDirs(FSImage.java:321)
        at org.apache.hadoop.hdfs.server.namenode.FSImage.recoverTransitionRead(FSImage.java:215)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFSImage(FSNamesystem.java:976)
        at org.apache.hadoop.hdfs.server.namenode.FSNamesystem.loadFromDisk(FSNamesystem.java:681)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.loadNamesystem(NameNode.java:584)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.initialize(NameNode.java:643)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:810)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.<init>(NameNode.java:794)
        at org.apache.hadoop.hdfs.server.namenode.NameNode.createNameNode(NameNode.java:1487)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNode(MiniDFSCluster.java:1111)
        at org.apache.hadoop.hdfs.MiniDFSCluster.createNameNodesAndSetConf(MiniDFSCluster.java:982)
        at org.apache.hadoop.hdfs.MiniDFSCluster.initMiniDFSCluster(MiniDFSCluster.java:811)
        at org.apache.hadoop.hdfs.MiniDFSCluster.<init>(MiniDFSCluster.java:471)
        at org.apache.hadoop.hdfs.MiniDFSCluster$Builder.build(MiniDFSCluster.java:430)
        at org.opencypher.spark.testing.fixture.MiniDFSClusterFixture$class.cluster(MiniDFSClusterFixture.scala:53)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.cluster$lzycompute(HdfsDataSourceAcceptance.scala:43)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.cluster(HdfsDataSourceAcceptance.scala:43)
        at org.opencypher.spark.testing.fixture.MiniDFSClusterFixture$class.clusterConfig(MiniDFSClusterFixture.scala:77)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.clusterConfig(HdfsDataSourceAcceptance.scala:43)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.resetHadoopConfig(HdfsDataSourceAcceptance.scala:72)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.create(HdfsDataSourceAcceptance.scala:63)
        at org.opencypher.okapi.testing.PGDSAcceptance$class.beforeEach(PGDSAcceptance.scala:68)
        at org.opencypher.spark.api.io.fs.hdfs.HdfsDataSourceAcceptance.beforeEach(HdfsDataSourceAcceptance.scala:43)
        at org.scalatest.BeforeAndAfterEach$class.runTest(BeforeAndAfterEach.scala:220)
       at org.opencypher.spark.testing.CAPSTestSuite.runTest(CAPSTestSuite.scala:34)
        at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
        at org.scalatest.FunSpecLike$$anonfun$runTests$1.apply(FunSpecLike.scala:497)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
        at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
        at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
        at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
        at org.scalatest.FunSpecLike$class.runTests(FunSpecLike.scala:497)
        at org.scalatest.FunSpec.runTests(FunSpec.scala:1630)
        at org.scalatest.Suite$class.run(Suite.scala:1147)
        at org.scalatest.FunSpec.org$scalatest$FunSpecLike$$super$run(FunSpec.scala:1630)
        at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
        at org.scalatest.FunSpecLike$$anonfun$run$1.apply(FunSpecLike.scala:501)
        at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
        at org.scalatest.FunSpecLike$class.run(FunSpecLike.scala:501)
        at org.opencypher.spark.testing.CAPSTestSuite.org$scalatest$BeforeAndAfterAll$$super$run(CAPSTestSuite.scala:34)
        at org.scalatest.BeforeAndAfterAll$class.liftedTree1$1(BeforeAndAfterAll.scala:213)
        at org.scalatest.BeforeAndAfterAll$class.run(BeforeAndAfterAll.scala:210)
        at org.opencypher.spark.testing.CAPSTestSuite.run(CAPSTestSuite.scala:34)
        at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1210)
        at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1257)
        at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1255)
        at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
        at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
        at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1255)
        at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
        at org.scalatest.Suite$class.run(Suite.scala:1144)
        at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
        at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
        at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1346)
        at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1340)
        at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
        at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
        at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1506)
         at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
         at org.scalatest.tools.Runner$.main(Runner.scala:827)
         at org.scalatest.tools.Runner.main(Runner.scala)

**Comment by HADDADENICAR** [comment] 2018-07-15 10:48
did the project works well in **linux** environment  ?

**Comment by pstutz** [comment] 2018-07-15 13:30
Hi Haddad, thanks for reporting the details. It does seem to be a Windows issue, on OS X and Linux the tests pass. We'll have to figure out how to best address this.

**Comment by pstutz** [comment] 2018-07-15 14:38
On StackOverflow it says that this error can happen when the [`%HADOOP_HOME%/bin` directory is not added to `PATH`](https://stackoverflow.com/questions/41851066/exception-in-thread-main-java-lang-unsatisfiedlinkerror-org-apache-hadoop-io).

It's still weird, because I would have expected the minicluster to use the non-native library instead in this case.

**Comment by pstutz** [comment] 2018-07-15 14:41
@HADDADENICAR Thank you for your feedback, this has been useful for us. I'm curious why you're interested in building the project yourself, wouldn't it be more convenient to use the Maven Central dependency instead?

**Comment by pstutz** [comment] 2018-07-15 17:53
Thanks a lot for reporting this. I managed to reproduce the problem here: https://github.com/opencypher/cypher-for-apache-spark/issues/559
This PR fixes the problem by explicitly setting the encoding to `UTF8`: https://github.com/opencypher/cypher-for-apache-spark/pull/560

**Comment by pstutz** [comment] 2018-07-16 10:46
@HADDADENICAR The two PRs with the resource leak and encoding fixes are both merged, please reopen if this hasn't been resolved. Thanks a lot for the feedback, this was helpful.

**Closed by pstutz** 2018-07-16 10:46 UTC

**Comment by HADDADENICAR** [comment] 2018-07-19 19:41
On Ubuntu i still get errors  too :

    TreeNodeTest:
    - aggregate
    - leaf
   - arity
   - height
    - lists of children
   - unsupported uses of lists of children *** FAILED ***
     "...on-child type: java.[base/java.]lang.String cannot b..." did not equal "...on-child type:   java.[]lang.String cannot b..." (

**Comment by Mats-SX** [comment] 2018-07-26 10:07
This comment resolved in #566
